### ISSUE TITLE
Random Input Crashes App

### ISSUE THREAD

**Issue by sgomez14** [ianjchadwick/P2_TWELP#1]
Entering random characters can crash the app. This can be resolved by sanitizing input so that it does not have prohibited characters.

Test input: !@#%$^%^&HTEwefadv

![twelp_crash](https://user-images.githubusercontent.com/30096097/139555369-f2d5498b-d60e-42c2-ac62-b06c8ebd175f.png)

**Comment by ianjchadwick** [comment]
Oooh... yeah, that's no good. I fixed that! Thanks!
